#:schema node_modules/wrangler/config-schema.json
name = "bgfs"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "a98dc34b8c5a4322b7f516232b441cc3" }
]

[assets]
directory = "./public"
